<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
    </PropertyGroup>

    <ItemGroup>
      <Page Update="Window\MainWindow.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\DB\DB.csproj" />
      <ProjectReference Include="..\GeneralElementsZapretUI\GeneralElementsZapretUI.csproj" />
      <ProjectReference Include="..\Zapret\Zapret.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Resources\Images\eye.png" />
      <Resource Include="Resources\Images\eye.png">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Resource>
    </ItemGroup>

</Project>
