// <auto-generated />
using System;
using DB.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DB.Entities
{
    [DbContext(typeof(ShowZapretDbContext))]
    partial class ShowZapretDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DB.Entities.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Note", (string)null);
                });

            modelBuilder.Entity("DB.Entities.Rule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("FreedomPunishInMonth")
                        .HasColumnType("float");

                    b.Property<double>("MoneyPunishmentInRubles")
                        .HasColumnType("float");

                    b.Property<string>("NameOfRule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RightWordNext")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RightWordPrevious")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("ThresholdForRightWordNext")
                        .HasColumnType("float");

                    b.Property<double?>("ThresholdForRightWordPrevious")
                        .HasColumnType("float");

                    b.Property<string>("TriggerWord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TriggerWordMatchThreshold")
                        .HasColumnType("float");

                    b.Property<int>("UserCreatorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserCreatorId");

                    b.ToTable("Rule", (string)null);
                });

            modelBuilder.Entity("DB.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("Role");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("DB.Entities.Note", b =>
                {
                    b.HasOne("DB.Entities.User", "User")
                        .WithMany("Notes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Note_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DB.Entities.Rule", b =>
                {
                    b.HasOne("DB.Entities.User", "UserCreator")
                        .WithMany("Rules")
                        .HasForeignKey("UserCreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserCreator");
                });

            modelBuilder.Entity("DB.Entities.User", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("Rules");
                });
#pragma warning restore 612, 618
        }
    }
}
